# Generated by Django 5.0.1 on 2024-01-29 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='address',
            new_name='salutation',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 1, 29, 1, 18, 0, 807873, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
    ]
